{% set version = "1.1.11.20250809" %}

package:
  name: types-html5lib
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-html5lib/types_html5lib-{{ version }}.tar.gz
    sha256: 7976ec7426bb009997dc5e072bca3ed988dd747d0cbfe093c7dfbd3d5ec8bf57
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/html5lib-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\html5lib-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for html5lib
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
