{% set version = "1.1.11.20240222" %}

package:
  name: types-html5lib
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/t/types-html5lib/types-html5lib-{{ version }}.tar.gz
    sha256: d9517ec6ba2fa1f63113e2930a59b60722a976cc983b94d7fd772f14865e1152
  - url: https://raw.githubusercontent.com/python/typeshed/main/LICENSE
    sha256: 295f8538c94ae5c3043301cf7cff1c852dab6a786a8ddee471e061b40d5ecabe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  commands:
    - pip check
    - test -f $SP_DIR/html5lib-stubs/__init__.pyi                 # [unix]
    - if not exist %SP_DIR%\\html5lib-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for html5lib
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
