# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.1.11.20251115"

package:
  name: types-html5lib
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/t/types-html5lib/types_html5lib-${{ version }}.tar.gz
    sha256: a4b666a06e496d7b2a9489dc9206f09a249fab7c62865ac6024cec24628b15d3

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }} >=77.0.3
    - setuptools
  run:
    - types-webencodings
    - python >=${{ python_min }}

tests:
  - package_contents:
      files:
        - site-packages/html5lib-stubs/__init__.pyi
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check

about:
  summary: Typing stubs for html5lib
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/mypy
